services:
  mock_acquiring_bank_api:
    image: mockoon/cli:1.5.0
    container_name: mock_acquiring_bank_api
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./acquiring-bank-mock-api.json:/data:ro
    command: -d data -i 0 -p 3000
