name: Build and Test .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore CKO.PaymentGateway.Challenge.sln
    - name: Build
      run: dotnet build --no-restore CKO.PaymentGateway.Challenge.sln
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~.UnitTests CKO.PaymentGateway.Challenge.sln
    - name: Run Acceptance Tests
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~.AcceptanceTests CKO.PaymentGateway.Challenge.sln
    - name: Run Architecture Tests
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~.ArchitectureTests CKO.PaymentGateway.Challenge.sln

    # cannot run this yet because docker on github actions takes time to get right :)
    # - name: Run Integration Tests
    #   run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~.IntegrationTests CKO.PaymentGateway.Challenge.sln
